import { Metadata } from 'next'
import MainLanding from '@/components/Landing/Main.landing'
import { buildMetadata } from '@/lib/seo'

export const metadata: Metadata = buildMetadata({
  title: 'FlowCraft — AI-Powered Diagram Generator',
  description:
    'FlowCraft creates flowcharts, sequence diagrams, user journey maps, mind maps, knowledge graphs, and more — generated by AI in seconds. No more dragging and dropping.',
  path: '/',
  keywords: [
    'ai flowchart generator',
    'diagram generator',
    'mermaid diagrams',
    'mind map ai',
    'flowcraft',
    'ai diagram tool',
  ],
})

export default async function Home() {
  return <MainLanding />
}
